Update Challenge_CN.txt
Mishasama/ProjectZomboidTranslations pull request #61
Opened 2020-04-20 08:01 UTC by HenryFishYu

Have not played the challenges due to really uncomfortable camera in version 41.

2020-04-23 14:05 UTC, Mishasama requested changes
RadioData_CN.txt 不放这里的，需要你自行存在gist里，然后把链接贴到issue里圈一下SK大佬看看他有什么办法。

2020-04-23 15:30 UTC, HenryFishYu commented
修改了，这样子ok吗，到时候一点一点翻译的话是直接在我的分支更新这个文本吗

2020-04-23 15:36 UTC, HenryFishYu commented
> RadioData_CN.txt 不放这里的，需要你自行存在gist里，然后把链接贴到issue里圈一下SK大佬看看他有什么办法。

SK大佬提取了，这个关了

2020-04-27 08:29 UTC, HenryFishYu commented
Challenge_CN还是要更新的

2020-04-28 11:23 UTC, Mishasama requested changes
还是有跟原文不一致的内容（或内容缺失）。
另外请在标点符号后面加上空格，以便启用自适应断行。

另外注意27和30官方是放反了作为陷阱的，翻译的时候最好不要打瞌睡，提交前如果能先检查甚至进游戏里校对一下就更好了。

2020-05-05 19:24 UTC, Mishasama commented
Outdated

2020-05-05 19:24 UTC, closed without merging